server:
  port: 8080

security:
  oauth2:
    resource:
      id: agora

  user:
    password: password

spring:
  datasource:
    url: jdbc:h2:mem:agoradb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: agora
    password:
  h2:
    console:
      enabled: true

client:
  id: agora
  secret: agora1234
